version: '3.8'

services:
  kivyapp:
    build: .
    container_name: kivyapp
    environment:
      - DISPLAY=host.docker.internal:0
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    ports:
      - "6000:6000"
    command: python3 main.py
